name: Deploy to VPS
#test it works
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" = "main" ]; then
            cd /var/www/umrah-prod
            git pull origin main
            pm2 restart umrah-prod
            else
            cd /var/www/umrah-staging
            git pull origin staging
            pm2 restart umrah-staging
            fi

